Update to version 0.4.0 fixed help directions and autostart service being improperly linked added new functions (update_config update_repo check_repo_ck) improved handling of errors and conditionals

diff --git a/src/linux-ck-autobuild b/src/linux-ck-autobuild
--- a/src/linux-ck-autobuild
+++ b/src/linux-ck-autobuild
@@ -1,6 +1,6 @@
 #!/bin/bash
 # linux-ck-autobuild
-VERSION=0.1.3
+VERSION=0.4.0
 # Author: Jochum D, jooch (at) gmx (dot) com
 # License: GPL3
 # About: This script will automatically build specified ck kernels
@@ -23,21 +23,23 @@ Options:
 --disable-autostart	Disable daemon (default)
 
 If you don't have a graphical environment you can use the systemd option:
-'systemctl enable $program_name@<username>.service'
+'systemctl enable $program_name@$USER.service'
 "
 exit 1
 }
 
-function enable_daemon {
-check_service="$(systemctl is-active $program_name.service)"
-[[ $check_service = "active" ]] && echo "ERROR: systemd service is currently enabled, you should disable that first." && exit 1 || false
+function enable_autostart {
+service_state="$(systemctl is-active linux-ck-autobuild@$USER.service)"
+if [[ $service_state = "active" ]] || [ -r /etc/systemd/system/multi-user.target.wants/linux-ck-autobuild@$USER.service ]; then
+	echo "ERROR: systemd service is currently enabled or active, you should disable that first." && exit 1
+else
 yes_or_no "$msg This will install the daemon into the user's autostart folder, proceed?" &&
 cp /etc/$program_name/$program_name-daemon.desktop /home/$USER/.config/autostart/$program_name-daemon.desktop
-echo "Installed $program_name-daemon.desktop in /home/$USER/.config/autostart"
-exit 1
+echo "Installed $program_name-daemon.desktop in /home/$USER/.config/autostart" && exit 1
+fi
 }
 
-function disable_daemon {
+function disable_autostart {
 yes_or_no "$msg This will remove the daemon from user's autostart folder, proceed?" &&
 rm /home/$USER/.config/autostart/$program_name-daemon.desktop
 echo "Removed $program_name-daemon.desktop from /home/$USER/.config/autostart"
@@ -57,6 +59,14 @@ function yes_or_no {
 function load_config {
 if [ -r /home/$USER/.config/$program_name/$program_name.conf ]; then
     . /home/$USER/.config/$program_name/$program_name.conf
+    if [ "$CONFIG_VERSION" == "$VERSION" ]; then
+		if [[ -z $editor || -z $BUILDDIR || -z $SUBARCH || -z $makeflags ]]; then
+		echo "ERROR: One or more settings are missing, please check your configuration." && exit 1
+		fi
+	else
+	update_config
+	fi
+
 else
 	. /etc/$program_name/default.conf
 	yes_or_no "$msg Configuration not found, copy default config?" &&
@@ -66,14 +76,35 @@ else
 fi
 }
 
+function update_config {
+
+UPDATE=( editor BUILDDIR USE_MODPROBE_DB maxload makeflags WATCHDOG_INTERVAL TIMEOUT TIMEOUT_UNIT POSTPONED USER_COMMAND1 USER_COMMAND2 USER_COMMAND3)
+
+mv /home/$USER/.config/$program_name/$program_name.conf /home/$USER/.config/$program_name/$program_name.old
+cp /etc/$program_name/default.conf /home/$USER/.config/$program_name/$program_name.conf
+
+for element in "${UPDATE[@]}"; do
+	sed -i '/^#/!s/'$element'=".*"/'$element'="'${!element}'"/g' /home/$USER/.config/$program_name/$program_name.conf
+done
+
+sed -i '/^#/!s/SUBARCH=(.*)/SUBARCH=( '"${SUBARCH[*]}"' )/g' /home/$USER/.config/$program_name/$program_name.conf
+echo "Config updated, you will need to restart this program manually." && exit 1
+}
+
 function edit_config {
 	if [ -r /usr/bin/$editor ]; then
 		$editor /home/$USER/.config/$program_name/$program_name.conf
 		. /home/$USER/.config/$program_name/$program_name.conf
 	else
-		echo "Please setup your config and restart:
-		/home/$USER/.config/$program_name/$program_name.conf"
+		echo -e "No editor found, please set your config in:\n/home/$USER/.config/$program_name/$program_name.conf"
 		exit 1
+	fi
+}
+
+function update_repo {
+	if [ -n "$USE_LOCAL_REPO" ]; then
+		mv $BUILDDIR/linux-ck/*$latest_version-x86_64.pkg.tar.zst $LOCAL_REPO
+		repo-add $LOCAL_REPO_DB $LOCAL_REPO/*$latest_version-x86_64.pkg.tar.zst
 	fi
 }
 
@@ -88,6 +119,24 @@ function check_build_dir {
 	git -C $BUILDDIR clone https://aur.archlinux.org/linux-ck.git --quiet
 	fi
 }
+
+function check_repo_ck {
+	curl_cmd="curl --head --fail --silent"
+	kernel=$($curl_cmd $repo_ck_mirror/linux-ck-${!subarch_name}-$latest_version-x86_64.pkg.tar.zst | grep 'HTTP/2 200')
+	headers=$($curl_cmd $repo_ck_mirror/linux-ck-${!subarch_name}-headers-$latest_version-x86_64.pkg.tar.zst | grep 'HTTP/2 200')
+	if [[ -n $kernel && $headers ]]; then
+	cd $BUILDDIR/linux-ck
+	if	[ -r $BUILDDIR/linux-ck/linux-ck-${!subarch_name}-$latest_version-x86_64.pkg.tar.zst ]; then
+		echo "Selected subarches found in build dir"
+		else
+		curl -O $repo_ck_mirror/linux-ck-${!subarch_name}-$latest_version-x86_64.pkg.tar.zst
+		curl -O $repo_ck_mirror/linux-ck-${!subarch_name}-headers-$latest_version-x86_64.pkg.tar.zst
+		fi
+	else
+	echo "Selected subarch not available in repo-ck"
+	fi
+}
+
 function main_program {
 	load_config
 	check_build_dir
@@ -96,23 +145,29 @@ function main_program {
 	sed -i '/^build().*/a MAKEFLAGS="'$makeflags'"' $BUILDDIR/linux-ck/PKGBUILD
 	for element in "${SUBARCH[@]}"; do
 		subarch_name="arch_$element"
-		if [ -z "$USE_MODPROBE_DB" ]; then 
-		sed -i '/pkgbase=/c\pkgbase=linux-ck-'${!subarch_name}'' $BUILDDIR/linux-ck/PKGBUILD
+		check_repo_ck
+		if	[ -r $BUILDDIR/linux-ck/linux-ck-${!subarch_name}-$latest_version-x86_64.pkg.tar.zst ]; then
+			echo "$(date +"%Y-%m-%d_%H:%M") Kernel fetched from repo-ck ${!subarch_name}-$latest_version > $BUILDDIR/linux-ck/linux-ck-${!subarch_name}-$latest_version.log"
 		else
-		sed -i '/pkgbase=/c\pkgbase=linux-ck-'${!subarch_name}'-modprobed' $BUILDDIR/linux-ck/PKGBUILD
+			if [ -z "$USE_MODPROBE_DB" ]; then 
+			sed -i '/pkgbase=/c\pkgbase=linux-ck-'${!subarch_name}'' $BUILDDIR/linux-ck/PKGBUILD
+			else
+			sed -i '/pkgbase=/c\pkgbase=linux-ck-'${!subarch_name}'-modprobed' $BUILDDIR/linux-ck/PKGBUILD
+			fi
+			sed -i '/_localmodcfg=/c\_localmodcfg='$USE_MODPROBE_DB'' $BUILDDIR/linux-ck/PKGBUILD
+			sed -i '/_subarch=/c\_subarch='$element'' $BUILDDIR/linux-ck/PKGBUILD
+			echo "$(date +"%Y-%m-%d_%H:%M") Starting kernel build ${!subarch_name}-$latest_version"
+			(cd $BUILDDIR/linux-ck && makepkg -C) > $BUILDDIR/linux-ck/linux-ck-${!subarch_name}-$latest_version.log
+			echo "$(date +"%Y-%m-%d_%H:%M") End kernel build ${!subarch_name}-$latest_version"
 		fi
-		sed -i '/_localmodcfg=/c\_localmodcfg='$USE_MODPROBE_DB'' $BUILDDIR/linux-ck/PKGBUILD
-		sed -i '/_subarch=/c\_subarch='$element'' $BUILDDIR/linux-ck/PKGBUILD
-		echo "$(date +"%Y-%m-%d_%H:%M") Starting kernel build ${!subarch_name}-$latest_version"
-		(cd $BUILDDIR/linux-ck && makepkg -C) > $BUILDDIR/linux-ck/linux-ck-${!subarch_name}-$latest_version.log
-		echo "$(date +"%Y-%m-%d_%H:%M") End kernel build ${!subarch_name}-$latest_version"
 	done
 	echo "$latest_version" > $BUILDDIR/linux-ck/.last_build
+	update_repo
 }
 
 [[ $1 = "-h" ]] && print_help || 
 [[ $1 = "--help" ]] && print_help || 
-[[ $1 = "--enable_autostart" ]] && enable_autostart || 
+[[ $1 = "--enable-autostart" ]] && enable_autostart || 
 [[ $1 = "--disable-autostart" ]] && disable_autostart || 
 [[ $1 = "-c" ]] && load_config && edit_config || 
 
